version: "2"
linters:
  default: all
  disable:
    - depguard
    - dupl
    - exhaustive
    - exhaustruct
    - ireturn
    - nlreturn
    - noinlineerr
    - paralleltest
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 17
    funlen:
      lines: 60
      statements: 45
      ignore-comments: true
    misspell:
      locale: US
      ignore-rules:
        - freedos
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupword
          - funlen
          - gocyclo
        path: _test\.go$
      - linters:
          - cyclop
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
